name: validate-primary-schema
run-name: Validate primary schema
on:
  push:
    paths:
      - 'schemas/schema.json'
    branches:
      - dev
jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: python -mjson.tool schemas/schema.json > /dev/null
